server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: menu-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/menu/**
          filters:
            - name: StripPrefix
              args:
                parts: 1

        - id: kitchen-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/kitchen/**
          filters:
            - name: StripPrefix
              args:
                parts: 1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG