server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: kitchen-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order
    username: postgres
    password: 5432
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: "kitchen"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/kitchen/db.changelog-master.yaml
    default-schema: "kitchen"
    contexts: dev
    user: postgres
    password: postgres
    url: ${spring.datasource.url}
    drop-first: false

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      pizzeria: DEBUG