server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=menu
    username: postgres
    password: 5432
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: menu
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/menu/db.changelog-master.yaml
    default-schema: menu
    contexts: dev
    user: postgres
    password: postgres
    url: ${spring.datasource.url}
    drop-first: false

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      pizzeria: DEBUG